### ISSUE TITLE
-v flag does not display version

### ISSUE THREAD

**Issue by mayank-Pareek** [theoforger/mastermind#2]
## Description:
The -v flag is expected to display the version of the CLI tool according to the release 0.1 requirements, but currently it is not recognized. The -V flag which is clap default, works and displays the version as intended. When trying to use -v, an error is thrown.
#### Screenshot:
![image](https://github.com/user-attachments/assets/d561fff9-9754-44e4-a8be-056413400278)

### Steps to reproduce:
1. Run the command: `cargo run -- -v`
2. Notice the error message:
   ```bash
   error: unexpected argument '-v' found
   ```
### Expected behavior: 
The -v flag should display the version of mastermind, as specified by release 0.1 requirements.

### Actual behavior: 
The -v flag throws an error, while the -V flag correctly displays the version.

## Environment:
- Operating System: Microsoft Windows 11
- Rust version: rustc 1.81.0 (eeb90cda1 2024-09-04)
- Version of Mastermind: 0.1.0

**Comment by theoforger** [comment]
This project uses [`clap`](https://lib.rs/crates/clap) for arguments handling. It is an upstream decision to use `-V` to display version number.

For more information, see: https://github.com/clap-rs/clap/issues/138

**Comment by mayank-Pareek** [comment]
As mentioned in the issue comments, the default can be overridden https://github.com/clap-rs/clap/issues/138#issuecomment-1557690932 . You can close this issue if you do not intend to override the default verbose option.

**Comment by theoforger** [comment]
I'll keep it this way to leave room for a possible `--verbose` option in the future. Appreciate the suggestion though 🙏
