### ISSUE TITLE
Add test case for build_request_body() 

### ISSUE THREAD

**Issue by mulla028** [theoforger/mastermind#21]
## Description 

Exploring your new unit tests I found that you don't have a test for `build_request_body()` inside of `src/api/chat_completions.rs`.
Please assign me to this issue. I would like to implement one test case 🧔‍♂️ 

## Steps to Achieve It

- [x] Using tokio test implement unit test
- [x] Run the test
- [ ] Edit in case of errors
- [x] Create a PR

**Comment by theoforger** [comment]
Sure! It's all yours 👌
